name: Code quality
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  check_code_quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: false
    - name: Install poetry
      run: pipx install poetry
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'poetry'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        python -m pip install nox_poetry
    - name: Lint
      run: nox -s style_checking
    - name: Type checking
      run: nox -s type_checking
    - name: Build docs
      run: nox -s build_docs

  doc_quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: false
    - name: Install poetry
      run: pipx install poetry
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'poetry'
    - name: Install dependencies
      run: |
        python -m pip install nox_poetry
        poetry install -v
    - name: Check doc quality
      run: |
        nox -s doctests
    - name: Check if docs build
      run: |
        nox -s build_docs
